controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_download_json:
    path: /download-json
    controller: App\Controller\ApiController::downloadJson