<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEiWRUfv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEiWRUfv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEiWRUfv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEiWRUfv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEiWRUfv\App_KernelDevDebugContainer([
    'container.build_hash' => 'EiWRUfv',
    'container.build_id' => '97dab313',
    'container.build_time' => 1725970358,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEiWRUfv');
