<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU50UAWQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU50UAWQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU50UAWQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU50UAWQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU50UAWQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'U50UAWQ',
    'container.build_id' => 'fb4cd540',
    'container.build_time' => 1727783807,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU50UAWQ');
