<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTNAVII5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTNAVII5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTNAVII5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTNAVII5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTNAVII5\App_KernelDevDebugContainer([
    'container.build_hash' => 'TNAVII5',
    'container.build_id' => 'c5dab89d',
    'container.build_time' => 1729590639,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTNAVII5');
